name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golanglint-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # pin@v5.0.1

      - name: SetUp and Build
        uses: ./.github/actions/setup

      - name: Dummy VERSION file
        run: echo "0.0.0" > ./VERSION

      - name: Setup Git Identity
        run: git config --global user.email "github-actions[bot]@users.noreply.github.com" && git config --global user.name "github-actions[bot]"

      - name: Run verify
        run: make verify-extended
        env:
          GOPATH: /home/runner/go
